### ISSUE TITLE
Possibilitar listar  registros do tipo LIS cadastrados no FI-admin por idioma

### ISSUE THREAD

**Issue by marcoslmori** [bireme/lis-wp-plugin#1]
Exemplo: 
Ao clicar em "ver todos" 
![image](https://user-images.githubusercontent.com/10047460/32071931-ac7b004c-ba6f-11e7-9e2a-a19233477024.png)

com o link de http://bvsalud.org/es/vitrinas

Recuperar somente registros em espanhol

![image](https://user-images.githubusercontent.com/10047460/32072032-05244c3a-ba70-11e7-8e43-4a5a61b7cbee.png)

**Comment by marcoslmori** [comment]
Será necessário criar um subportal para cada idioma

**Comment by wilsonmoura** [comment]
@marcoslmori nesse caso, o mais indicado seria a implementação de um filtro/cluster com base no idioma dos documentos. Favor confirmar se está de acordo para que possamos avançar nessa atividade.

**Comment by wilsonmoura** [comment]
@marcoslmori nesse caso, o mais indicado é implementar de um filtro/cluster com base no idioma dos documentos.

**Comment by wilsonmoura** [comment]
@marcoslmori nesse caso, o mais indicado é implementar um filtro/cluster com base no idioma dos documentos.

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor validar.
