### ISSUE TITLE
Descritor Betacoronavírus traz resultado negativo na busca do plug-in

### ISSUE THREAD

**Issue by suelisuga** [bireme/lis-wp-plugin#11]
Prezados,

Conforme informado no chamado plug-in multimedia, o descritor Betacoronavirus não é localizado na busca dos plug-ins LIS e Multimedia. 
=>https://github.com/bireme/fi-multimedia-wp-plugin/issues/18

![image](https://user-images.githubusercontent.com/13105683/75886586-38dcd500-5e07-11ea-9f28-d63436116ba0.png)

Muito obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Correção aplicada para o índice de registros LIS do FI-ADMIN.
