### ISSUE TITLE
Criar cluster de Área Temática

### ISSUE THREAD

**Issue by suelisuga** [bireme/lis-wp-plugin#19]
Solicito criar cluster de Área Temática (até 20 opções e incluir opção Ver todas)

Contexto: Portal de vitrines do conhecimento

Muito obrigada
Sueli

**Comment by marcoslmori** [comment]
@viniciusandrade alguma novidade sobre essa implementação?

**Comment by suelisuga** [comment]
Aguardando @marcoslmori para atualização na instancia de teste

**Comment by marcoslmori** [comment]
@suelisuga atualizei a BVS Brasil, tem prioritariamente atualizar em mais alguma instância?  https://brasil.teste.bvs.br/lis
