### ISSUE TITLE
Plugin do lis não funciona com o enlace permanente "Nome da Entrada"

### ISSUE THREAD

**Issue by marcoslmori** [bireme/lis-wp-plugin#2]
Caso: mtci.bvsalud.org

Configuração do enlace permanente:  Nome da Entrada

Configuração do Plugin:  Página do Plugin: lis

Acesso ao plugin: http://mtci.hom.bvsalud.org/lis/

Erro: 
"This is somewhat embarrassing, isn’t it?
It seems we can’t find what you’re looking for. Perhaps searching can help."

Ao mudar a configuração do enlace permanente para "dia e nome" funciona corretamente.

**Comment by viniciusandrade** [comment]
@marcoslmori 

Ajustes realizados no plugin. Favor atualizar na instância de homologação e realizar novo teste.

**Comment by marcoslmori** [comment]
Pelos testes que fizemos funcionou corretamente com a configuração dos links permanentes para o nome da entrada como no dia e nome. 

![image](https://user-images.githubusercontent.com/10047460/37846865-bf5ecace-2ead-11e8-9d6e-d49c65ae219f.png)

**Comment by viniciusandrade** [comment]
OK. Obrigada por confirmar.
