### ISSUE TITLE
Erro crítico

### ISSUE THREAD

**Issue by ajuniorgithub** [bireme/lis-wp-plugin#22]
Após a atualização do PHP para a versão 8.2 este plugin passou a exibir a mensagem "Há um erro crítico no seu site."

**Comment by ajuniorgithub** [comment]
Deprecated: Creation of dynamic property AIOSEO\Plugin\Lite\Admin\PostSettings::$integrations is deprecated in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/all-in-one-seo-pack/app/AIOSEO.php on line 248

Warning: Undefined array key "REDIRECT_URL" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-widgets/servplat_login_widget.php on line 4

Warning: Undefined array key "show_calendar" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/direve/calendar/wp-calendar.php on line 73

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/better-wp-security/core/core.php on line 1102

Warning: Undefined array key "pagename" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/fi-multimedia/fi-multimedia.php on line 97

Warning: Undefined array key "language" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-themes/bvs-2012/bireme_archives/admin_configs.php on line 16

Warning: Undefined array key "title_view" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-themes/bvs-2012/bireme_archives/admin_configs.php on line 17

Warning: Undefined array key "contactPage" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-themes/bvs-2012/bireme_archives/admin_configs.php on line 22

Warning: Undefined array key "loginMenu" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-themes/bvs-2012/bireme_archives/admin_configs.php on line 40

Warning: Trying to access array offset on value of type bool in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-site.php on line 76

Warning: Undefined array key "pagename" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/fi-multimedia/fi-multimedia.php on line 220
Deprecated: Creation of dynamic property SiteOrigin_Panels::$container is deprecated in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/siteorigin-panels/siteorigin-panels.php on line 558
class="home blog mega-menu-max-mega-menu-1 full-width custom-font-enabled single-author">

**Comment by ajuniorgithub** [comment]
Deprecated: Creation of dynamic property AIOSEO\Plugin\Lite\Admin\PostSettings::$integrations is deprecated in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/all-in-one-seo-pack/app/AIOSEO.php on line 248

Warning: Undefined array key "REDIRECT_URL" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin/bvs-widgets/servplat_login_widget.php on line 4

Warning: Undefined array key "show_calendar" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/direve/calendar/wp-calendar.php on line 73

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/better-wp-security/core/core.php on line 1102
﻿
Warning: Undefined array key "s" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/template/lis-home.php on line 16

Warning: Undefined array key "newexpr" in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/template/lis-home.php on line 16

Deprecated: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/lib/Paginator.php on line 21

Warning: Undefined property: Paginator::$count in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/lib/Paginator.php on line 23

Fatal error: Uncaught DivisionByZeroError: Division by zero in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/lib/Paginator.php:23 Stack trace: #0 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/template/lis-home.php(54): Paginator->paginate() #1 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/lis.php(124): include('...') #2 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-includes/class-wp-hook.php(308): LIS_Plugin->template_redirect() #3 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #4 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-includes/plugin.php(517): WP_Hook->do_action() #5 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-includes/template-loader.php(13): do_action() #6 /dados/sites/www.bvsdip.icict.fiocruz.br/wp-blog-header.php(19): require_once('...') #7 /dados/sites/www.bvsdip.icict.fiocruz.br/index.php(17): require('...') #8 {main} thrown in /dados/sites/www.bvsdip.icict.fiocruz.br/wp-content/plugins/lis/lib/Paginator.php on line 23

**Comment by wilsonmoura** [comment]
@ajuniorgithub provavelmente o plugin deve estar desatualizado. Favor atualizar o plugin e testar novamente.

**Comment by ajuniorgithub** [comment]
Erro crítico deixou de ocorrer.
