### ISSUE TITLE
Erro na opção = Sugira um site

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/lis-wp-plugin#23]
Alves, Marilda Perez (BIR)
Para:Antonio, Vinicius Andrade (BIR)
Cc:#BIR:Lilacs;Suga, Sueli Mitiko Yano (BIR)
Sex, 31/3/2023 12:13
=Vinicius, Boa Tarde!

Alguma posição sobre o erro relatado?

Obrigada!
Marilda Perez Alves

De: Alves, Marilda Perez (BIR) <alvesma@paho.org>
Enviado: quarta-feira, 15 de março de 2023 14:23
Para: Antonio, Vinicius Andrade (BIR) <antoniov@paho.org>
Cc: #BIR:Lilacs <bir.lilacs@paho.org>
Assunto: Erro envio de Sugestão LIS
 =Vinicius, 

Por favor verificar a página abaixo que apresenta erro:

https://bvsalud.org/portal-lis/lis-search/suggest-site

Quando tentamos enviar/finalizar o formulário de sugestão LIS informa:

![image](https://user-images.githubusercontent.com/38661168/235762679-a4ae03ff-5f81-4890-a47d-63e289ca1f55.png)

Obrigada!
Abs
Marilda Perez Alves

**Comment by viniciusandrade** [comment]
Ajuste aplicado em ambiente de testes.

Aberto chamado Ocomon (9390) para atualização em produção. Assim que concluído eu informo por aqui.

**Comment by alvesmarilda** [comment]
Teste  realizado com sucesso.

Obrigada!

**Comment by alvesmarilda** [comment]
@viniciusandrade 
Como relatado no chamado do DirEve (https://fi-admin.bvsalud.org/suggested-event/edit/807#tab-descriptors),  o mesmo erro está ocorrendo no momento de gravar para o Status recusado.

![image](https://github.com/bireme/lis-wp-plugin/assets/38661168/300bfb0f-aab9-48c9-b431-180f9d7fcf7a)


Exemplo: 

![image](https://github.com/bireme/lis-wp-plugin/assets/38661168/36c85511-1565-4def-91b8-8efc1bb464c4)

Apesar do erro informado finaliza para o Status  "recusado".

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda ajuste aplicado no sistema, quando possível favor validar. Obrigado.

**Comment by alvesmarilda** [comment]
@viniciusandrade 

Teste efetuado com sucesso.

Obrigada!
