### ISSUE TITLE
Padronizar tamanho de imagem WordPress/LIS

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/lis-wp-plugin#29]
Colegas,

Favor verificar a questão da padronização de imagens no WordPress LIS.

https://bvsalud.org/portal-lis/
Destaques
![image](https://github.com/bireme/lis-wp-plugin/assets/38661168/2d8bcd10-1190-41a0-b91f-13ab92ccb0e1)

![image](https://github.com/bireme/lis-wp-plugin/assets/38661168/2314fbd4-6e21-41ba-88b2-a7f614ed8692)

Obrigada!

**Comment by suelisuga** [comment]
@marcioalvessilva o principal seria atualizar o WP ou corrigir o problema para que não precisemos editar a imagem todas as vezes. Poderia verificar? Quer que eu abra chamado no repositorio WP themes?

Obrigada

**Comment by marcioalvessilva** [comment]
Boa tarde, o mandei para o Jefferson todas  imagens no mesmo tamanho, isso corrige a visualização nesse momento e quando tiver novas imagens podem me acionar, é uma atividade rápida, até que seja feita essa analise, pelo Mori, sobre motivo que não esta mais permitindo fazer o recorte, segundo ele pode ser permissão na pasta ou atualização.

**Comment by marcioalvessilva** [comment]
Issue finalizado, continuo à disposição!
